// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKJTIXFahLBeZzDsflwWFO6mpq_DM_HL8',
    appId: '1:382607300214:android:9ea487174af3e52358b157',
    messagingSenderId: '382607300214',
    projectId: 'memory-game-58c95',
    storageBucket: 'memory-game-58c95.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMn1NKYiC2agfsrWjTBbT3jHCRbh6JfO8',
    appId: '1:382607300214:ios:cd193b89b652ee9358b157',
    messagingSenderId: '382607300214',
    projectId: 'memory-game-58c95',
    storageBucket: 'memory-game-58c95.firebasestorage.app',
    androidClientId: '382607300214-9d2mrjoqtbmpl654ehb0duq4g7dbibp2.apps.googleusercontent.com',
    iosClientId: '382607300214-0hh4uegptsaqbi93bv71563j9jkugms6.apps.googleusercontent.com',
    iosBundleId: 'com.goldmagnetsoft.memoryGame',
  );

}